#include <iostream>
#include <string>
#include <algorithm>
#include <cstdio>
#include <dos.h>
#include <unistd.h>                //LIBRARIES
#include <conio.h>
#include <windows.h>
#include <fstream>
using namespace std ;
void list(){
	int filter;
	cout<<"\n" ;
	cout<<"\t\t\t*********************"<<endl ;
    cout<<"\t\t\t~PROPERTIES FOR RENT~"<<endl ;
    cout<<"\t\t\t*********************"<<endl ;
	cout<<"\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 1 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<<endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 2"<<endl ;
	cout<<"\nAddress : Railway Road , Peshawar" << endl ;
	cout<<"\nRent : 20,000 "<<endl ;
	cout<<"\nName:M.Rafiq\tcontact: +92-3357906625 "<< endl ;
	cout<<"\nPress Enter To show Another" << endl ;
	getch();	                                  //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 2 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<<endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 2"<<endl ;
	cout<<"\nAddress : Nishterabad , Peshawar" << endl ;
	cout<<"\nRent : 20,000 "<<endl ;
	cout<<"\nName:Atif Ifthikar\tcontact: +923008591591, +923005900327 "<< endl ;
	cout<<"\nPress Enter To show Another" << endl ;
	getch();                                   //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 3 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulberg Road,Gulberg No 1 , Peshawar " << endl ;
	cout<<"\nRent : 26,000"<<endl ;
	cout<<"\nName:Nasih Ullah Jan\tcontact: +923136445715, +923369245715"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;                                //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 4 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla"<< endl ;
	cout<<"\nBedrooms = 7\tWashrooms = 6 "<< endl ;
	cout<<"\nAddress : Hayatabad phase-6,Sector F-5 , Peshawar " << endl ;
	cout<<"\nRent : 85,000"<<endl ;
	cout<<"\nName:Laitf Ullah \tcontact: +923119111905"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;                             //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 5 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla"<< endl ;
	cout<<"\nBedrooms = 7\tWashrooms = 6 "<< endl ;
	cout<<"\nAddress : Hayatabad phase-6,Sector F-5 , Peshawar " << endl ;
	cout<<"\nRent : 85,000"<<endl ;
	cout<<"\nName:Laitf Ullah \tcontact: +923119111905"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;                          //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 6 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 1 Kanal"<< endl ;
	cout<<"\nBedrooms = 10\tWashrooms = 10 "<< endl ;
	cout<<"\nAddress : Hayatabad Phase 2,Sector H-4 , Peshawar " << endl ;
	cout<<"\nRent : 1.2 Lakh"<<endl ;
	cout<<"\nName:Naseer Ahmad\tcontact: +923338089099"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();                            //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 7 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 6 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : University Town ,Town Heights, Peshawar " << endl ;
	cout<<"\nRent : 35,OOO"<<endl ;
	cout<<"\nName:Meezan Shah\tcontact: +923332218288, +923335960738"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();                            //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 8 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 4 "<< endl ;
	cout<<"\nAddress : 	Hayatabad pahse-6,sector f-6, street no 12,house no 32, Peshawar " << endl ;
	cout<<"\nRent : 50,OOO"<<endl ;
	cout<<"\nName:Ali Rehman Yousafzai\tcontact: +92915863297"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();       
		cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 9 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : 	University Town, Circular Road, Peshawar " << endl ;
	cout<<"\nRent : 40,OOO"<<endl ;
	cout<<"\nName:Muhammad Sadiq\tcontact: +923357906625"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();                            //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 10 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla"<< endl ;
	cout<<"\nBedrooms = 1\tWashrooms = 1 "<< endl ;
	cout<<"\nAddress : 	University Town, Town Heights , Peshawar " << endl ;
	cout<<"\nRent : 25,OOO"<<endl ;
	cout<<"\nName:Meezan Shah\tcontact: +92915844479"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();  
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 11 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<<endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 2"<<endl ;
	cout<<"\nAddress : Nishterabad , Peshawar" << endl ;
	cout<<"\nRent : 20,000 "<<endl ;
	cout<<"\nName:Atif Ifthikar\tcontact: +923008591591, +923005900327 "<< endl ;
	cout<<"\nPress Enter To show Another" << endl ;
	getch();     
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 12 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulberg Road,Gulberg No 1 , Peshawar " << endl ;
	cout<<"\nRent : 26,000"<<endl ;
	cout<<"\nName:Nasih Ullah Jan\tcontact: +923136445715, +923369245715"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;    
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 13 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : Bamba Road, Madina Street, Gulberg No 2 , Peshawar " << endl ;
	cout<<"\nRent : 20,000"<<endl ;
	cout<<"\nName:Naseer Khan\tcontact: +923136445715"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;     
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 14 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulberg No 3, Izzat Khan Chowk, Peshawar " << endl ;
	cout<<"\nRent : 32,000"<<endl ;
	cout<<"\nName:Nasih Ullah Jan\tcontact: +923136445715, +923369245715"<<endl ;
    cout<<"\nPres Enter To show Another" << endl ;
    getch() ;  
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 15 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 2 Marla"<< endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 1 "<< endl ;
	cout<<"\nAddress : Talab Road, Nothia Qadeem, Saddar, Peshawar " << endl ;
	cout<<"\nRent : 20,000"<<endl ;
	cout<<"\nName:Naseeb Ullah \tcontact: +923119111905"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;  
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 16 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla"<< endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 1 "<< endl ;
	cout<<"\nAddress : Fuwara Chowk, Saddar, Peshawar " << endl ;
	cout<<"\nRent : 25,000"<<endl ;
	cout<<"\nName:Vikram  \tcontact: +923178334216"<<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 17 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla"<< endl ;
	cout<<"\nBedrooms = 5\tWashrooms = 5 "<< endl ;
	cout<<"\nAddress : Gulbahar, Peshawar " << endl ;
	cout<<"\nRent : 40,000"<<endl ;
	cout<<"\nName:Hamayun Shah \tcontact: +923002824207"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ; 
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 18 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 4 "<< endl ;
	cout<<"\nAddress : Gulbahar, Peshawar " << endl ;
	cout<<"\nRent : 25,000"<<endl ;
	cout<<"\nName:Hamayun Shah \tcontact: +923002824207"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;  
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 19 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : Rahatabad, Amin Road, Peshawar " << endl ;
	cout<<"\nRent : 30,000"<<endl ;
	cout<<"\nName:Muhammad Shahzad \tcontact: +923315185544"<<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;   
	cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tHOUSE NO 20 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 1.2 kanal"<< endl ;
	cout<<"\nBedrooms = 8\tWashrooms = 7 "<< endl ;
	cout<<"\nAddress : Rahatabad, Thaykaydaran Hujra Road, Peshawar " << endl ;
	cout<<"\nRent : 80,000"<<endl ;
	cout<<"\nName:Syed Gohar Ali Shah \tcontact: +923009596905"<<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tHOUSE NO 21 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : Rahatabad, Peshawar " << endl ;
	cout<<"\nRent : 20,000"<<endl ;
	cout<<"\nName:Syed Gohar Ali Shah \tcontact: +923009596905"<<endl ;      
    cout<<"\t\t\t*********************"<<endl ;
    cout<<"\t\t\t~PROPERTIES FOR SALE~"<<endl ;
    cout<<"\t\t\t*********************"<<endl ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 1 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 12 Marla "<<endl;
	cout<<"\nAddress: Fowara Chowk, Saddar, Peshawar"<<endl ;
	cout<<"\nPrice:3.5 Crore"<<endl;
	cout<<"\nName:Muhammad Saeed \t Contact: +923468883003,+923347575588 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 2 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4 Marla "<<endl;
	cout<<"\nAddress: Cantt mall, Fakhr-e-Alam Road, Saddar, Peshawar"<<endl ;
	cout<<"\nPrice:95 Lakh"<<endl;
	cout<<"\nName:Amir Shuja \t Contact: +923189191691 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 3 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 1.1 Crore"<<endl;
	cout<<"\nName:Muhammad Rehman \t Contact: +923049498085 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 4 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 80 Lakh "<<endl;
	cout<<"\nName:Alamzaib Khan \t Contact: +923335957532 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 5 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 6 Marla "<<endl;
	cout<<"\nAddress: Saddar Town, Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 95 Lakh "<<endl;
	cout<<"\nName:Ahmad \t Contact: +923309501313 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 6 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 6.5 Marla "<<endl;
	cout<<"\nAddress: Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 2 Crore "<<endl;
	cout<<"\nName:Osman Khan Niazi \t Contact: +923023952526 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 7 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Khyber Heights, Peshawar"<<endl ;
	cout<<"\nPrice: 78 Lakh "<<endl;
	cout<<"\nName:Tasleem Khan \t Contact: +923330662873 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 8 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 6 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Peshawar Heights, Peshawar"<<endl ;
	cout<<"\nPrice: 88 Lakh "<<endl;
	cout<<"\nName:Shabir Ahmad Khan \t Contact: +923339122127 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 9 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4.9 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Peshawar Heights, Peshawar"<<endl ;
	cout<<"\nPrice: 79 Lakh "<<endl;
	cout<<"\nName:Taimur Ahmad \t Contact: +923460019107 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 10 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 7 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 1.2 Crore "<<endl;
	cout<<"\nName:Zahid Khan Khalil \t Contact: +923009535353,+923169535353 " <<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 11 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4.5 Marla "<<endl;
	cout<<"\nAddress: Yakatoot, Peshawar"<<endl ;
	cout<<"\nPrice: 1.7 Crore "<<endl;
	cout<<"\nName:Ali Ahmad Irfan \t Contact: +923139607338" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 12 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 2 Marla "<<endl;
	cout<<"\nAddress: Yakatoot, Peshawar"<<endl ;
	cout<<"\nPrice: 52 Lakh "<<endl;
	cout<<"\nName:Ali Ahmad Irfan \t Contact: +923139607338" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 13 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4.5 Marla "<<endl;
	cout<<"\nAddress: Yakatoot, Peshawar"<<endl ;
	cout<<"\nPrice: 1 Crore "<<endl;
	cout<<"\nName:Ehsan Ali \t Contact: +923139502383" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
	cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 14 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4.7 Marla "<<endl;
	cout<<"\nAddress: Main Road,Gulberg No 1, Peshawar"<<endl ;
	cout<<"\nPrice: 70 Lakh "<<endl;
	cout<<"\nName:Meezan Ullah \t Contact: +923332218288,+923335960738" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 15 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Main Road,Gulberg No 1, Peshawar"<<endl ;
	cout<<"\nPrice: 30 Lakh "<<endl;
	cout<<"\nName:Meezan Ullah \t Contact: +923332218288,+923335960738" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 16 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Madni Chowk,Gulberg No 1, Peshawar"<<endl ;
	cout<<"\nPrice: 55 Lakh "<<endl;
	cout<<"\nName:Sami Ullah \t Contact: +92915844479" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 17 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Main Lezat Khan Chowk,Gulberg No 3, Peshawar"<<endl ;
	cout<<"\nPrice: 90 Lakh "<<endl;
	cout<<"\nName:Nasir Ullah \t Contact: +923369245715" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
	cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 18 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 10 Marla "<<endl;
	cout<<"\nAddress: Nouman Town,Streer No 1,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 1.4 Crore "<<endl;
	cout<<"\nName:Imran Khan \t Contact: +923122212339" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 19 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 6 Marla "<<endl;
	cout<<"\nAddress: Nouman Town,Streer No 1,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 1 Crore "<<endl;
	cout<<"\nName:Imran Khan \t Contact: +923122212339" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 20 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4 Marla "<<endl;
	cout<<"\nAddress: Malik Saad Town,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 78 Lakh "<<endl;
	cout<<"\nName:Imran Ullah \t Contact: +923339124342" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 21 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Khan Bahadur Colony,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 60 Lakh "<<endl;
	cout<<"\nName:Fayaz Khan \t Contact: +923139992594" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 22 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Gulbahar,Dhayre Road, Peshawar"<<endl ;
	cout<<"\nPrice: 1.45 Crore "<<endl;
	cout<<"\nName:Fasi Ullah \t Contact: +923366444498,+923127772333" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
	cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 23 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Gulbahar,cinema Road, Peshawar"<<endl ;
	cout<<"\nPrice: 1.9 Crore "<<endl;
	cout<<"\nName:Bilal Muhammadzai \t Contact: +923005244461" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 24 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5.5 Marla "<<endl;
	cout<<"\nAddress: Gulbahar,cinema Road, Peshawar"<<endl ;
	cout<<"\nPrice: 1.8 Crore "<<endl;
	cout<<"\nName:Bilal Jan \t Contact: +923005424262" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
	cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 25 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Phase 7,Sector E-5,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 2.25 Crore "<<endl;
	cout<<"\nName:Ali Akbar Afridi \t Contact: +923449107769,+923005862945" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 26 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Phase 6,Sector F9,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 1.8 Crore "<<endl;
	cout<<"\nName:Murad Ali \t Contact: +923335829155" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 27 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 1 Kanal "<<endl;
	cout<<"\nAddress: Phase 6,Sector F2,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 5.75 Crore "<<endl;
	cout<<"\nName:Muhammad Khan \t Contact: +923339252084,+923159252084" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 28 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 10 Marla "<<endl;
	cout<<"\nAddress: Phase 4,Sector N2,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 4.2 Crore "<<endl;
	cout<<"\nName:Salman Javed\t Contact: +923345500556,+923469529244" <<endl ;
}
void rent(){
	int filter;
	cout<<"\n" ;
	cout<<"\t\t\t*********************"<<endl ;
    cout<<"\t\t\t~PROPERTIES FOR RENT~"<<endl ;
    cout<<"\t\t\t*********************"<<endl ;
	cout<<"\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 1 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<<endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 2"<<endl ;
	cout<<"\nAddress : Railway Road , Peshawar" << endl ;
	cout<<"\nRent : 20,000 "<<endl ;
	cout<<"\nName:M.Rafiq\tcontact: +92-3357906625 "<< endl ;
	cout<<"\nPress Enter To show Another" << endl ;
	getch();	                                  //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 2 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<<endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 2"<<endl ;
	cout<<"\nAddress : Nishterabad , Peshawar" << endl ;
	cout<<"\nRent : 20,000 "<<endl ;
	cout<<"\nName:Atif Ifthikar\tcontact: +923008591591, +923005900327 "<< endl ;
	cout<<"\nPress Enter To show Another" << endl ;
	getch();                                   //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 3 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulberg Road,Gulberg No 1 , Peshawar " << endl ;
	cout<<"\nRent : 26,000"<<endl ;
	cout<<"\nName:Nasih Ullah Jan\tcontact: +923136445715, +923369245715"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;                                //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 4 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla"<< endl ;
	cout<<"\nBedrooms = 7\tWashrooms = 6 "<< endl ;
	cout<<"\nAddress : Hayatabad phase-6,Sector F-5 , Peshawar " << endl ;
	cout<<"\nRent : 85,000"<<endl ;
	cout<<"\nName:Laitf Ullah \tcontact: +923119111905"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;                             //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 5 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla"<< endl ;
	cout<<"\nBedrooms = 7\tWashrooms = 6 "<< endl ;
	cout<<"\nAddress : Hayatabad phase-6,Sector F-5 , Peshawar " << endl ;
	cout<<"\nRent : 85,000"<<endl ;
	cout<<"\nName:Laitf Ullah \tcontact: +923119111905"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;                          //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 6 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 1 Kanal"<< endl ;
	cout<<"\nBedrooms = 10\tWashrooms = 10 "<< endl ;
	cout<<"\nAddress : Hayatabad Phase 2,Sector H-4 , Peshawar " << endl ;
	cout<<"\nRent : 1.2 Lakh"<<endl ;
	cout<<"\nName:Naseer Ahmad\tcontact: +923338089099"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();                            //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 7 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 6 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : University Town ,Town Heights, Peshawar " << endl ;
	cout<<"\nRent : 35,OOO"<<endl ;
	cout<<"\nName:Meezan Shah\tcontact: +923332218288, +923335960738"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();                            //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 8 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 4 "<< endl ;
	cout<<"\nAddress : 	Hayatabad pahse-6,sector f-6, street no 12,house no 32, Peshawar " << endl ;
	cout<<"\nRent : 50,OOO"<<endl ;
	cout<<"\nName:Ali Rehman Yousafzai\tcontact: +92915863297"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();       
		cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 9 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : 	University Town, Circular Road, Peshawar " << endl ;
	cout<<"\nRent : 40,OOO"<<endl ;
	cout<<"\nName:Muhammad Sadiq\tcontact: +923357906625"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();                            //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 10 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla"<< endl ;
	cout<<"\nBedrooms = 1\tWashrooms = 1 "<< endl ;
	cout<<"\nAddress : 	University Town, Town Heights , Peshawar " << endl ;
	cout<<"\nRent : 25,OOO"<<endl ;
	cout<<"\nName:Meezan Shah\tcontact: +92915844479"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();  
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 11 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<<endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 2"<<endl ;
	cout<<"\nAddress : Nishterabad , Peshawar" << endl ;
	cout<<"\nRent : 20,000 "<<endl ;
	cout<<"\nName:Atif Ifthikar\tcontact: +923008591591, +923005900327 "<< endl ;
	cout<<"\nPress Enter To show Another" << endl ;
	getch();     
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 12 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulberg Road,Gulberg No 1 , Peshawar " << endl ;
	cout<<"\nRent : 26,000"<<endl ;
	cout<<"\nName:Nasih Ullah Jan\tcontact: +923136445715, +923369245715"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;    
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 13 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : Bamba Road, Madina Street, Gulberg No 2 , Peshawar " << endl ;
	cout<<"\nRent : 20,000"<<endl ;
	cout<<"\nName:Naseer Khan\tcontact: +923136445715"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;     
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 14 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulberg No 3, Izzat Khan Chowk, Peshawar " << endl ;
	cout<<"\nRent : 32,000"<<endl ;
	cout<<"\nName:Nasih Ullah Jan\tcontact: +923136445715, +923369245715"<<endl ;
    cout<<"\nPres Enter To show Another" << endl ;
    getch() ;  
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 15 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 2 Marla"<< endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 1 "<< endl ;
	cout<<"\nAddress : Talab Road, Nothia Qadeem, Saddar, Peshawar " << endl ;
	cout<<"\nRent : 20,000"<<endl ;
	cout<<"\nName:Naseeb Ullah \tcontact: +923119111905"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;  
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 16 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla"<< endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 1 "<< endl ;
	cout<<"\nAddress : Fuwara Chowk, Saddar, Peshawar " << endl ;
	cout<<"\nRent : 25,000"<<endl ;
	cout<<"\nName:Vikram  \tcontact: +923178334216"<<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 17 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla"<< endl ;
	cout<<"\nBedrooms = 5\tWashrooms = 5 "<< endl ;
	cout<<"\nAddress : Gulbahar, Peshawar " << endl ;
	cout<<"\nRent : 40,000"<<endl ;
	cout<<"\nName:Hamayun Shah \tcontact: +923002824207"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ; 
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 18 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 4 "<< endl ;
	cout<<"\nAddress : Gulbahar, Peshawar " << endl ;
	cout<<"\nRent : 25,000"<<endl ;
	cout<<"\nName:Hamayun Shah \tcontact: +923002824207"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;  
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 19 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : Rahatabad, Amin Road, Peshawar " << endl ;
	cout<<"\nRent : 30,000"<<endl ;
	cout<<"\nName:Muhammad Shahzad \tcontact: +923315185544"<<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;   
	cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tHOUSE NO 20 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 1.2 kanal"<< endl ;
	cout<<"\nBedrooms = 8\tWashrooms = 7 "<< endl ;
	cout<<"\nAddress : Rahatabad, Thaykaydaran Hujra Road, Peshawar " << endl ;
	cout<<"\nRent : 80,000"<<endl ;
	cout<<"\nName:Syed Gohar Ali Shah \tcontact: +923009596905"<<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tHOUSE NO 21 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : Rahatabad, Peshawar " << endl ;
	cout<<"\nRent : 20,000"<<endl ;
	cout<<"\nName:Syed Gohar Ali Shah \tcontact: +923009596905"<<endl ;
}
 void sale(){
 cout<<"\t\t\t*********************"<<endl ;
    cout<<"\t\t\t~PROPERTIES FOR SALE~"<<endl ;
    cout<<"\t\t\t*********************"<<endl ;
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tPROPERTY NO 1 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 12 Marla "<<endl;
	cout<<"\nAddress: Fowara Chowk, Saddar, Peshawar"<<endl ;
	cout<<"\nPrice:3.5 Crore"<<endl;
	cout<<"\nName:Muhammad Saeed \t Contact: +923468883003,+923347575588 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tPROPERTY NO 2 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla "<<endl;
	cout<<"\nAddress: Cantt mall, Fakhr-e-Alam Road, Saddar, Peshawar"<<endl ;
	cout<<"\nPrice:95 Lakh"<<endl;
	cout<<"\nName:Amir Shuja \t Contact: +923189191691 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tPROPERTY NO 3 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 1.1 Crore"<<endl;
	cout<<"\nName:Muhammad Rehman \t Contact: +923049498085 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tPROPERTY NO 4 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 80 Lakh "<<endl;
	cout<<"\nName:Alamzaib Khan \t Contact: +923335957532 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tPROPERTY NO 5 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 6 Marla "<<endl;
	cout<<"\nAddress: Saddar Town, Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 95 Lakh "<<endl;
	cout<<"\nName:Ahmad \t Contact: +923309501313 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tPROPERTY NO 6 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 6.5 Marla "<<endl;
	cout<<"\nAddress: Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 2 Crore "<<endl;
	cout<<"\nName:Osman Khan Niazi \t Contact: +923023952526 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 7 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Khyber Heights, Peshawar"<<endl ;
	cout<<"\nPrice: 78 Lakh "<<endl;
	cout<<"\nName:Tasleem Khan \t Contact: +923330662873 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 8 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 6 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Peshawar Heights, Peshawar"<<endl ;
	cout<<"\nPrice: 88 Lakh "<<endl;
	cout<<"\nName:Shabir Ahmad Khan \t Contact: +923339122127 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 9 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4.9 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Peshawar Heights, Peshawar"<<endl ;
	cout<<"\nPrice: 79 Lakh "<<endl;
	cout<<"\nName:Taimur Ahmad \t Contact: +923460019107 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 10 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 1.2 Crore "<<endl;
	cout<<"\nName:Zahid Khan Khalil \t Contact: +923009535353,+923169535353 " <<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 11 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4.5 Marla "<<endl;
	cout<<"\nAddress: Yakatoot, Peshawar"<<endl ;
	cout<<"\nPrice: 1.7 Crore "<<endl;
	cout<<"\nName:Ali Ahmad Irfan \t Contact: +923139607338" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 12 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 2 Marla "<<endl;
	cout<<"\nAddress: Yakatoot, Peshawar"<<endl ;
	cout<<"\nPrice: 52 Lakh "<<endl;
	cout<<"\nName:Ali Ahmad Irfan \t Contact: +923139607338" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 13 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4.5 Marla "<<endl;
	cout<<"\nAddress: Yakatoot, Peshawar"<<endl ;
	cout<<"\nPrice: 1 Crore "<<endl;
	cout<<"\nName:Ehsan Ali \t Contact: +923139502383" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
	cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 14 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4.7 Marla "<<endl;
	cout<<"\nAddress: Main Road,Gulberg No 1, Peshawar"<<endl ;
	cout<<"\nPrice: 70 Lakh "<<endl;
	cout<<"\nName:Meezan Ullah \t Contact: +923332218288,+923335960738" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 15 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Main Road,Gulberg No 1, Peshawar"<<endl ;
	cout<<"\nPrice: 30 Lakh "<<endl;
	cout<<"\nName:Meezan Ullah \t Contact: +923332218288,+923335960738" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 16 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Madni Chowk,Gulberg No 1, Peshawar"<<endl ;
	cout<<"\nPrice: 55 Lakh "<<endl;
	cout<<"\nName:Sami Ullah \t Contact: +92915844479" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 17 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Main Lezat Khan Chowk,Gulberg No 3, Peshawar"<<endl ;
	cout<<"\nPrice: 90 Lakh "<<endl;
	cout<<"\nName:Nasir Ullah \t Contact: +923369245715" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
	cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 18 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 10 Marla "<<endl;
	cout<<"\nAddress: Nouman Town,Streer No 1,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 1.4 Crore "<<endl;
	cout<<"\nName:Imran Khan \t Contact: +923122212339" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 19 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 6 Marla "<<endl;
	cout<<"\nAddress: Nouman Town,Streer No 1,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 1 Crore "<<endl;
	cout<<"\nName:Imran Khan \t Contact: +923122212339" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 20 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla "<<endl;
	cout<<"\nAddress: Malik Saad Town,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 78 Lakh "<<endl;
	cout<<"\nName:Imran Ullah \t Contact: +923339124342" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 21 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Khan Bahadur Colony,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 60 Lakh "<<endl;
	cout<<"\nName:Fayaz Khan \t Contact: +923139992594" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tPROPERTY NO 22 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Gulbahar,Dhayre Road, Peshawar"<<endl ;
	cout<<"\nPrice: 1.45 Crore "<<endl;
	cout<<"\nName:Fasi Ullah \t Contact: +923366444498,+923127772333" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
	cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 23 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Gulbahar,cinema Road, Peshawar"<<endl ;
	cout<<"\nPrice: 1.9 Crore "<<endl;
	cout<<"\nName:Bilal Muhammadzai \t Contact: +923005244461" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 24 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5.5 Marla "<<endl;
	cout<<"\nAddress: Gulbahar,cinema Road, Peshawar"<<endl ;
	cout<<"\nPrice: 1.8 Crore "<<endl;
	cout<<"\nName:Bilal Jan \t Contact: +923005424262" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
	cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 25 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Phase 7,Sector E-5,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 2.25 Crore "<<endl;
	cout<<"\nName:Ali Akbar Afridi \t Contact: +923449107769,+923005862945" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 26 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Phase 6,Sector F9,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 1.8 Crore "<<endl;
	cout<<"\nName:Murad Ali \t Contact: +923335829155" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 27 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 1 Kanal "<<endl;
	cout<<"\nAddress: Phase 6,Sector F2,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 5.75 Crore "<<endl;
	cout<<"\nName:Muhammad Khan \t Contact: +923339252084,+923159252084" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 28 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 10 Marla "<<endl;
	cout<<"\nAddress: Phase 4,Sector N2,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 4.2 Crore "<<endl;
	cout<<"\nName:Salman Javed\t Contact: +923345500556,+923469529244" <<endl ;
}
int main(){
	system("color 70");                      //USED FOR BACKGROUND AND FONT COLOR
	int search1,choice,a,i,x,n,y,filter,beds,number;
	string search,Peshawar,property ;
	char area[20];
	char name[50];
	char address[150];
	float demand ;
	cout<<"\n";
	cout<<"\n";
	cout<<"\t\t\t ************************"<<endl;
	cout<<"\t\t\t*                        *" <<endl ;
	cout<<"\t\t\t*  LOADING PLEASE WAIT   *"<<endl ;
	cout<<"\t\t\t*                        *" <<endl ;
	cout<<"\t\t\t ************************"<<endl;
	cout<<"\n" << endl ;
	cout<<"\n"<<endl ;
	sleep(2);
    for(int j=0;j<80;j++){
    cout<<"_";
    Sleep(70);
    }
    system("cls");
	sleep(2);
	cout<<"()    ()    () ()()()() ()          ()()()() ()()()() ()()      ()() ()()()() "<<endl;  
	cout<<"()    ()    () ()       ()         ()        ()    () () ()    () () ()"<<endl;
	cout<<"()    ()    () ()()()() ()         ()        ()    () ()  ()()()  () ()()()() "<<endl;
	cout<<"()    ()    () ()       ()         ()        ()    () ()          () ()        ";
	cout<<" ()()()()()()() ()()()() ()()()()()  ()()()() ()()()() ()          () ()()()()  ";
	sleep(2);                               //USED FOR GIVING A GAP BETWEEN 2 STATEMENTS 
	system("cls") ;                         //A PRE-DEFINED FUNCTION FOR CLEARING THE SCREEN
	cout<<"\n" ;
	cout<<"\t\t Need a place ? So you can call it " << endl ;
	cout<<"\n" ;
	cout<<"\t\t\tHOME SWEET HOME"<<endl ;
	cout<<"\n" ;
	cout<<"\t\tOr are you dreaming of becoming a landlord"<<endl ;
	cout<<"\n";
	cout<<"\t\t Well then you are in the right place !! " << endl ;
	cout<<"\n" ;
	cout<<"\tLet's Go together through the homes and lands of your choice " << endl ;
	cout<<"\n " << endl;
	cout<<"\t\t \t*************" <<endl ;
	cout<<"\t\t \t    START    " << endl ;
	cout<<"\t\t \t*************" <<endl ;
	cout<<"\t\t \t<Enter 1> " ;
	cin>>x;
	system("cls");
	do{                                        /*USING DO-WHILE LOOP FOR THE GIVEN CONDITION AND REPITION OF MENU*/
	if(x==1){                                       
	cout<<"\t\t\t********************"<<endl ;
	cout<<"\t\t\t SYED'S REAL ESTATE " << endl ;
	cout<<"\t\t\t********************"<<endl ;
	cout<<"\t\t1.To Find Property For Rent (Enter 1) " << endl ;
	cout<<"\n\t\t2.To Find Property For Sale (Enter 2)" << endl ;
	cout<<"\n\t\t3.To Show All Property Availabe For Rent And Sale (Enter 3)" << endl ;
	cout<<"\n\t\t4.To Give Feedback (Enter 4)" << endl ;
	cout<<"\n\t\t5.To See Feedbacks (Enter 5)" << endl ;
	cout<<"\n\t\t6.To Know About The Programmer (Enter 6) "<<endl ;
	cout<<"\n\t\t7.For My Mentors (Enter 7) " <<endl ;
    cout<<"\n\t\t\t ENTER CHOICE : " ;
    cin>>choice ;
    system("cls");
    sleep(2);
    if(choice==1){                                         //USING IF-ELSE STATEMENTS
	cout<<"\t\t\t*********************"<<endl ;
    cout<<"\t\t\t~PROPERTIES FOR RENT~"<<endl ;
    cout<<"\t\t\t*********************"<<endl ;
	cout<<"\n\t Search By Area(enter 0)   \tSearch By Beds(enter 1)" << endl ;
	cout<<"\n\t\t To Show All Property For Rent(enter 3)" <<endl;
	cout<<"\n\t\t\t  To Go Back(enter 2)"<< endl ;
	cout<<"\n\t\t\tENTER CHOICE : " ;
	cin>>filter ;
	system("cls") ;
	if(filter==0){                                   //USING NESTED IF
	cout<<"\n\t\t\t\t\t\t\t AVAILABLE AREAS " << endl ;
	cout<<"\n\t\t\t\t\t\t\t1.Nishterabad." ;
	cout<<"\n\t\t\t\t\t\t\t2.Hayatabad." ;
	cout<<"\n\t\t\t\t\t\t\t3.Gulberg." ;
	cout<<"\n\t\t\t\t\t\t\t4.Saddar.";
	cout<<"\n\t\t\t\t\t\t\t5.Rahatabad.";
	cout<<"\n\t\t\t\t\t\t\t6.Gulbahar.";
	cout<<"\n\tPlease Enter Area : " ;
	cin>>search;
	transform(search.begin(),search.end(),search.begin(), ::toupper);
	system("cls");
	if(search=="NISHTERABAD"){                                 //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 1 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<<endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 2"<<endl ;
	cout<<"\nAddress : Nishterabad , Peshawar" << endl ;
	cout<<"\nRent : 20,000 "<<endl ;
	cout<<"\nName:Atif Ifthikar\tcontact: +923008591591, +923005900327 "<< endl ;
	cout<<"\nPress Enter To show Another" << endl ;
	getch();        //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls"); 
}
    if(search=="GULBERG"){
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 1 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulberg Road,Gulberg No 1 , Peshawar " << endl ;
	cout<<"\nRent : 26,000"<<endl ;
	cout<<"\nName:Nasih Ullah Jan\tcontact: +923136445715, +923369245715"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;                                //getch() A PRE-DEFINED FUNCTION USED FOR TAKING A CHARACTER AS INPUT TO CONTINUE//
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 2 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : Bamba Road, Madina Street, Gulberg No 2 , Peshawar " << endl ;
	cout<<"\nRent : 20,000"<<endl ;
	cout<<"\nName:Naseer Khan\tcontact: +923136445715"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;     
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 3 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulberg No 1 , Peshawar " << endl ;
	cout<<"\nRent : 18,000"<<endl ;
	cout<<"\nName:Jamal Shah\tcontact: +923139648348"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;  
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 4 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulberg No 3, Izzat Khan Chowk, Peshawar " << endl ;
	cout<<"\nRent : 32,000"<<endl ;
	cout<<"\nName:Nasih Ullah Jan\tcontact: +923136445715, +923369245715"<<endl ;  
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ; 
	cin>>filter ;
	system("cls");
}

	if(search=="HAYATABAD"){
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 1 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 4 "<< endl ;
	cout<<"\nAddress : 	Hayatabad pahse-6,sector f-6, street no 12,house no 32, Peshawar " << endl ;
	cout<<"\nRent : 50,OOO"<<endl ;
	cout<<"\nName:Ali Rehman Yousafzai\tcontact: +92915863297"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch();       
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 2 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 1 Kanal"<< endl ;
	cout<<"\nBedrooms = 10\tWashrooms = 10 "<< endl ;
	cout<<"\nAddress : Hayatabad Phase 2,Sector H-4 , Peshawar " << endl ;
	cout<<"\nRent : 1.2 Lakh"<<endl ;
	cout<<"\nName:Naseer Ahmad\tcontact: +923338089099"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch(); 
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 3 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla"<< endl ;
	cout<<"\nBedrooms = 7\tWashrooms = 6 "<< endl ;
	cout<<"\nAddress : Hayatabad phase-6,Sector F-5 , Peshawar " << endl ;
	cout<<"\nRent : 85,000"<<endl ;
	cout<<"\nName:Laitf Ullah \tcontact: +923119111905"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;    
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 4 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 1 Kanal"<< endl ;
	cout<<"\nBedrooms = 7\tWashrooms = 7 "<< endl ;
	cout<<"\nAddress : Hayatabad phase-6,Sector F-4 , Peshawar " << endl ;
	cout<<"\nRent : 55,000"<<endl ;
	cout<<"\nName:Ahmad Zahid \tcontact: +923338089099"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;    
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 5 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla"<< endl ;
	cout<<"\nBedrooms = 6\tWashrooms = 5 "<< endl ;
	cout<<"\nAddress : Hayatabad phase-6,Sector F-10 , Peshawar " << endl ;
	cout<<"\nRent : 47,000"<<endl ;
	cout<<"\nName:Najeeb Ullah Khan \tcontact: +923331583834"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;   
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 6 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Hayatabad phase-7,Sector E-5 , Peshawar " << endl ;
	cout<<"\nRent : 30,000"<<endl ;
	cout<<"\nName:Najeeb Ullah Khan \tcontact: +923331583834"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;   
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");                              
}
	if(search=="SADDAR"){
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 1 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 2 Marla"<< endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 1 "<< endl ;
	cout<<"\nAddress : Talab Road, Nothia Qadeem, Saddar, Peshawar " << endl ;
	cout<<"\nRent : 20,000"<<endl ;
	cout<<"\nName:Naseeb Ullah \tcontact: +923119111905"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ;  
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 2 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla"<< endl ;
	cout<<"\nBedrooms = 2\tWashrooms = 1 "<< endl ;
	cout<<"\nAddress : Fuwara Chowk, Saddar, Peshawar " << endl ;
	cout<<"\nRent : 25,000"<<endl ;
	cout<<"\nName:Vikram  \tcontact: +923178334216"<<endl ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
	if(search=="GULBAHAR"){
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 1 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 7 Marla"<< endl ;
	cout<<"\nBedrooms = 5\tWashrooms = 5 "<< endl ;
	cout<<"\nAddress : Gulbahar, Peshawar " << endl ;
	cout<<"\nRent : 40,000"<<endl ;
	cout<<"\nName:Hamayun Shah \tcontact: +923002824207"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ; 
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 2 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 3 "<< endl ;
	cout<<"\nAddress : Gulbahar, Peshawar " << endl ;
	cout<<"\nRent : 30,000"<<endl ;
	cout<<"\nName:Hamayun Shah \tcontact: +923002824207"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ; 
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 3 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 4\tWashrooms = 4 "<< endl ;
	cout<<"\nAddress : Gulbahar, Peshawar " << endl ;
	cout<<"\nRent : 25,000"<<endl ;
	cout<<"\nName:Hamayun Shah \tcontact: +923002824207"<<endl ;
    cout<<"\nPress Enter To show Another" << endl ;
    getch() ; 
    cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 4 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 6 Marla"<< endl ;
	cout<<"\nBedrooms = 6\tWashrooms = 6 "<< endl ;
	cout<<"\nAddress : Gulbahar, Peshawar " << endl ;
	cout<<"\nRent : 60,000"<<endl ;
	cout<<"\nName:Hamayun Shah \tcontact: +923002824207"<<endl ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
	}
	if(search=="RAHATABAD"){
	cout<<"\n\t\t**********" << endl ;
	cout<<"\t\tHOUSE NO 1 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 5 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : Rahatabad, Amin Road, Peshawar " << endl ;
	cout<<"\nRent : 30,000"<<endl ;
	cout<<"\nName:Muhammad Shahzad \tcontact: +923315185544"<<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tHOUSE NO 2 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 1.2 kanal"<< endl ;
	cout<<"\nBedrooms = 8\tWashrooms = 7 "<< endl ;
	cout<<"\nAddress : Rahatabad, Thaykaydaran Hujra Road, Peshawar " << endl ;
	cout<<"\nRent : 80,000"<<endl ;
	cout<<"\nName:Syed Gohar Ali Shah \tcontact: +923009596905"<<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tHOUSE NO 3 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 4 Marla"<< endl ;
	cout<<"\nBedrooms = 3\tWashrooms = 2 "<< endl ;
	cout<<"\nAddress : Rahatabad, Peshawar " << endl ;
	cout<<"\nRent : 20,000"<<endl ;
	cout<<"\nName:Syed Gohar Ali Shah \tcontact: +923009596905"<<endl ;
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}	
}
	if(filter==3){
	rent();
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
	}
	if(filter==1){
	cout<<"\n\tNOTE:We Only Have Houses Of 1-2-3-4-5-7-8 and 10 Rooms Yet"<<endl ;
	cout<<"\n\t\tHow Many Rooms Would Meet Your Needs ? "<<endl  ;
	cout<<"\n\t\tEnter The Number Of Rooms : " ;
	cin>>beds ;
	system("cls");
	if(beds==1){
    fstream beds1 ;
	cout<<"\n\t\tPlease Wait While We Redirect You Towards Your Demand " << endl ;
	sleep(3) ;
	system("CLS") ;
	beds1.open("beds1.txt",ios::in);
	string line ;
	while(!beds1.eof()){
    getline(beds1,line);
    cout<<line<<endl;
}
	beds1.close() ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
	if (beds==2){	
	fstream beds2 ;
	cout<<"\n\t\tPlease Wait While We Redirect You Towards Your Demand " << endl ;
	sleep(3) ;
	system("CLS") ;
	beds2.open("beds2.txt",ios::in);
	string line ;
	while(!beds2.eof()){
    getline(beds2,line);
    cout<<line<<endl;
}
	beds2.close() ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
    if(beds==3){
    fstream beds3 ;
	cout<<"\n\t\tPlease Wait While We Redirect You Towards Your Demand " << endl ;
	sleep(3) ;
	system("CLS") ;
	beds3.open("beds3.txt",ios::in);
	string line ;
	while(!beds3.eof()){
    getline(beds3,line);
    cout<<line<<endl;
}
	beds3.close() ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");    	
	}
	if(beds==4){
	fstream beds4 ;
	cout<<"\n\t\tPlease Wait While We Redirect You Towards Your Demand " << endl ;
	sleep(3) ;
	system("CLS") ;
	beds4.open("beds4.txt",ios::in);
	string line ;
	while(!beds4.eof()){
    getline(beds4,line);
    cout<<line<<endl;
}
	beds4.close() ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");    	
	}
	if(beds==5){
	fstream beds5 ;
	cout<<"\n\t\tPlease Wait While We Redirect You Towards Your Demand " << endl ;
	sleep(3) ;
	system("CLS") ;
	beds5.open("beds5.txt",ios::in);
	string line ;
	while(!beds5.eof()){
    getline(beds5,line);
    cout<<line<<endl;
}
	beds5.close() ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");    	
}    	

	if (beds==7){
	fstream beds7 ;
	cout<<"\n\t\tPlease Wait While We Redirect You Towards Your Demand " << endl ;
	sleep(3) ;
	system("CLS") ;
	beds7.open("beds7.txt",ios::in);
	string line ;
	while(!beds7.eof()){
    getline(beds7,line);
    cout<<line<<endl;
}
	beds7.close() ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls"); 
	}
	if(beds==8){
	fstream beds8 ;
	cout<<"\n\t\tPlease Wait While We Redirect You Towards Your Demand " << endl ;
	sleep(3) ;
	system("CLS") ;
	beds8.open("beds8.txt",ios::in);
	string line ;
	while(!beds8.eof()){
    getline(beds8,line);
    cout<<line<<endl;
}
	beds8.close() ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
	}
	if(beds==10){
	fstream beds10 ;
	cout<<"\n\t\tPlease Wait While We Redirect You Towards Your Demand " << endl ;
	sleep(3) ;
	system("CLS") ;
	beds10.open("beds10.txt",ios::in);
	string line ;
	while(!beds10.eof()){
    getline(beds10,line);
    cout<<line<<endl;
}
	beds10.close() ;
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
}
}
if(choice==3){
	list();
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}

}
  
    if(choice==2){
	cout<<"\t\t\t*********************"<<endl ;
    cout<<"\t\t\t~PROPERTIES FOR SALE~"<<endl ;
    cout<<"\t\t\t*********************"<<endl ;
    cout<<"\n\tTo Search By Area(enter 0) \t To Show All Property For Sale(enter 1)"<<endl ;
    cout<<"\n\t\t\t To Go Back(enter 2)"<<endl ;
    cout<<"\n\t\tENTER CHOICE : " ;
	cin>>filter ;
	system("cls");
	if(filter==0){                                   //USING NESTED IF

	cout<<"\n\t\t\t\t\t\t\t AVAILABLE AREAS " << endl ;
	cout<<"\n\t\t\t\t\t\t\t1.Saddar." ;
	cout<<"\n\t\t\t\t\t\t\t2.Rahatabad." ;
	cout<<"\n\t\t\t\t\t\t\t3.Yakatoot." ;
	cout<<"\n\t\t\t\t\t\t\t4.Gulberg.";
	cout<<"\n\t\t\t\t\t\t\t5.Doranpur.";
	cout<<"\n\t\t\t\t\t\t\t6.Gulbahar.";
	cout<<"\n\tPlease Enter Area : " ;
	cin>>search;
	transform(search.begin(),search.end(),search.begin(), ::toupper);
	system("cls");
	if(search=="SADDAR"){
	cout<<"\n\t\t*************" << endl ;
	cout<<"\t\tPROPERTY NO 1 " << endl ;
	cout<<"\n\t\t*************" <<endl ;
	cout<<"\nCovered Area : 12 Marla "<<endl;
	cout<<"\nAddress: Fowara Chowk, Saddar, Peshawar"<<endl ;
	cout<<"\nPrice:3.5 Crore"<<endl;
	cout<<"\nName:Muhammad Saeed \t Contact: +923468883003,+923347575588 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 2 " << endl ;
	cout<<"\n\t\t************" <<endl ;
	cout<<"\nCovered Area : 4 Marla "<<endl;
	cout<<"\nAddress: Cantt mall, Fakhr-e-Alam Road, Saddar, Peshawar"<<endl ;
	cout<<"\nPrice:95 Lakh"<<endl;
	cout<<"\nName:Amir Shuja \t Contact: +923189191691 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 3 " << endl ;
    cout<<"\n\t\t************" << endl ;  
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 1.1 Crore"<<endl;
	cout<<"\nName:Muhammad Rehman \t Contact: +923049498085 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 4 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 80 Lakh "<<endl;
	cout<<"\nName:Alamzaib Khan \t Contact: +923335957532 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 5 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 6 Marla "<<endl;
	cout<<"\nAddress: Saddar Town, Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 95 Lakh "<<endl;
	cout<<"\nName:Ahmad \t Contact: +923309501313 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\t\tPROPERTY NO 6 " << endl ;
    cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 6.5 Marla "<<endl;
	cout<<"\nAddress: Saddar, Peshawar"<<endl ;
	cout<<"\nPrice: 2 Crore "<<endl;
	cout<<"\nName:Osman Khan Niazi \t Contact: +923023952526 " <<endl ;
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
    if(search=="RAHATABAD"){
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 1 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Khyber Heights, Peshawar"<<endl ;
	cout<<"\nPrice: 78 Lakh "<<endl;
	cout<<"\nName:Tasleem Khan \t Contact: +923330662873 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 2 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 6 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Peshawar Heights, Peshawar"<<endl ;
	cout<<"\nPrice: 88 Lakh "<<endl;
	cout<<"\nName:Shabir Ahmad Khan \t Contact: +923339122127 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 3 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4.9 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Peshawar Heights, Peshawar"<<endl ;
	cout<<"\nPrice: 79 Lakh "<<endl;
	cout<<"\nName:Taimur Ahmad \t Contact: +923460019107 " <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 4 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 7 Marla "<<endl;
	cout<<"\nAddress: Rahatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 1.2 Crore "<<endl;
	cout<<"\nName:Zahid Khan Khalil \t Contact: +923009535353,+923169535353 " <<endl ;
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");    
}
    if(search=="YAKATOOT"){
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 1 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4.5 Marla "<<endl;
	cout<<"\nAddress: Yakatoot, Peshawar"<<endl ;
	cout<<"\nPrice: 1.7 Crore "<<endl;
	cout<<"\nName:Ali Ahmad Irfan \t Contact: +923139607338" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 2 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 2 Marla "<<endl;
	cout<<"\nAddress: Yakatoot, Peshawar"<<endl ;
	cout<<"\nPrice: 52 Lakh "<<endl;
	cout<<"\nName:Ali Ahmad Irfan \t Contact: +923139607338" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 3 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4.5 Marla "<<endl;
	cout<<"\nAddress: Yakatoot, Peshawar"<<endl ;
	cout<<"\nPrice: 1 Crore "<<endl;
	cout<<"\nName:Ehsan Ali \t Contact: +923139502383" <<endl ;
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");       	
}
    if(search=="GULBERG"){
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 1 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4.7 Marla "<<endl;
	cout<<"\nAddress: Main Road,Gulberg No 1, Peshawar"<<endl ;
	cout<<"\nPrice: 70 Lakh "<<endl;
	cout<<"\nName:Meezan Ullah \t Contact: +923332218288,+923335960738" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t**********" << endl ;
    cout<<"\t\tPROPERTY NO 2 " << endl ;
	cout<<"\t\t**********" <<endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Main Road,Gulberg No 1, Peshawar"<<endl ;
	cout<<"\nPrice: 30 Lakh "<<endl;
	cout<<"\nName:Meezan Ullah \t Contact: +923332218288,+923335960738" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 3 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Madni Chowk,Gulberg No 1, Peshawar"<<endl ;
	cout<<"\nPrice: 55 Lakh "<<endl;
	cout<<"\nName:Sami Ullah \t Contact: +92915844479" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 4 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Main Lezat Khan Chowk,Gulberg No 3, Peshawar"<<endl ;
	cout<<"\nPrice: 90 Lakh "<<endl;
	cout<<"\nName:Nasir Ullah \t Contact: +923369245715" <<endl ;
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
	if (search=="DORANPUR"){
	cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 1 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 10 Marla "<<endl;
	cout<<"\nAddress: Nouman Town,Streer No 1,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 1.4 Crore "<<endl;
	cout<<"\nName:Imran Khan \t Contact: +923122212339" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 2 " << endl ;
	cout<<"\n\t\t************" << endl ; ;
	cout<<"\nCovered Area : 6 Marla "<<endl;
	cout<<"\nAddress: Nouman Town,Streer No 1,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 1 Crore "<<endl;
	cout<<"\nName:Imran Khan \t Contact: +923122212339" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 3 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 4 Marla "<<endl;
	cout<<"\nAddress: Malik Saad Town,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 78 Lakh "<<endl;
	cout<<"\nName:Imran Ullah \t Contact: +923339124342" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 4 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Khan Bahadur Colony,Doranpur, Peshawar"<<endl ;
	cout<<"\nPrice: 60 Lakh "<<endl;
	cout<<"\nName:Fayaz Khan \t Contact: +923139992594" <<endl ;
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");	
}
    if (search=="GULBAHAR"){
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 1 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 3 Marla "<<endl;
	cout<<"\nAddress: Gulbahar,Dhayre Road, Peshawar"<<endl ;
	cout<<"\nPrice: 1.45 Crore "<<endl;
	cout<<"\nName:Fasi Ullah \t Contact: +923366444498,+923127772333" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
	cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 2 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Gulbahar,cinema Road, Peshawar"<<endl ;
	cout<<"\nPrice: 1.9 Crore "<<endl;
	cout<<"\nName:Bilal Muhammadzai \t Contact: +923005244461" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 3 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5.5 Marla "<<endl;
	cout<<"\nAddress: Gulbahar,cinema Road, Peshawar"<<endl ;
	cout<<"\nPrice: 1.8 Crore "<<endl;
	cout<<"\nName:Bilal Jan \t Contact: +923005424262" <<endl ;
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");	
}
    if (search=="HAYATABAD"){
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 1 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Phase 7,Sector E-5,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 2.25 Crore "<<endl;
	cout<<"\nName:Ali Akbar Afridi \t Contact: +923449107769,+923005862945" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 2 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 5 Marla "<<endl;
	cout<<"\nAddress: Phase 6,Sector F9,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 1.8 Crore "<<endl;
	cout<<"\nName:Murad Ali \t Contact: +923335829155" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 3 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 1 Kanal "<<endl;
	cout<<"\nAddress: Phase 6,Sector F2,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 5.75 Crore "<<endl;
	cout<<"\nName:Muhammad Khan \t Contact: +923339252084,+923159252084" <<endl ;
	cout<<"\nPress Enter To show Another" << endl ;
    getch() ;
    cout<<"\n\t\t************" << endl ;
    cout<<"\t\tPROPERTY NO 4 " << endl ;
	cout<<"\n\t\t************" << endl ;
	cout<<"\nCovered Area : 10 Marla "<<endl;
	cout<<"\nAddress: Phase 4,Sector N2,Hayatabad, Peshawar"<<endl ;
	cout<<"\nPrice: 4.2 Crore "<<endl;
	cout<<"\nName:Salman Javed\t Contact: +923345500556,+923469529244" <<endl ;
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
}
    if(filter==1){
	sale();
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
}
	
    if(choice==4){
	float rate ;
	char rec[60],adrs[60],name[25];
	cout<<"\t\t*********"<<endl ;
	cout<<"\t\t FEEDBACK " <<endl ;
	cout<<"\t\t*********"<<endl ;
	cout<<"\nKindly Fill Out This Short Survey " <<endl ;
	cout<<"\nPress Enter To Continue"<<endl ;
	getch();
	system("cls");
	fstream feedback;
	feedback.open("feedback.txt",ios::out | ios::app);
	cout<<"Q1)Please Enter Your Full Name"<<endl ;
	cin.ignore();
	cin.getline(name,25);
	cout<<"\nQ2)Where Are You From ?"<<endl ;
	cin.getline(adrs,100);
	cout<<"\nQ3)What Is Your Reccomendation For This Program ?"<<endl ;
	cin.getline(rec,100);
	cout<<"\nQ4)On a scale Of 1-10 What Will You Rate Us ?"<<endl ;
	cin>>rate;
	cout<<"\t\t\t**************"<<endl ;
	cout<<"\t\t\t THANK YOU !!!" <<endl ;
	cout<<"\t\t\t**************"<<endl ;
	feedback<<"Name : "<<name <<endl  ;
	feedback<<"\nAddress : "<<adrs<<endl ;
	feedback<<"\nReccomendation : "<<rec <<endl ;
	feedback<<"\nRatings : " <<rate<<"/10"<<endl ;
	feedback<<"*******************************************************************************"<<endl ;
	feedback.close();
    cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
    if(choice==5){
    cout<<"\t\t\t********************"<<endl ;
	cout<<"\t\t\tCUSTOMER'S FEEDBACK " <<endl ;
	cout<<"\t\t\t********************"<<endl ;
	fstream feedback ;
	cout<<"\nLOADING THE FEEDBACKS PLEASE WAIT  " << endl ;
	sleep(2) ;
	system("CLS") ;
	feedback.open("feedback.txt",ios::in);
	string line ;
	while(!feedback.eof()){
    getline(feedback,line);
    cout<<line<<endl;
	
}
	feedback.close() ;
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
}
    if(choice==6){
    cout<<"\t\t\t********************"<<endl ;
	cout<<"\t\t\t  ABOUT PROGRAMMER " <<endl ;
	cout<<"\t\t\t********************"<<endl ;
	cout<<"\n\t\tNAME : Syed Hussain Shah " << endl ;
	cout<<"\n\t\tAGE : 21 " <<endl ;
	cout<<"\n\t\tNATIONALITY : Pakistani" <<endl ;
	cout<<"\n\t\tQUALIFICATION : Currently Studying Data Science " <<endl ;
	cout<<"\n\t\tUNIVERSITY : IMSciences" <<endl ;
	cout<<"\n\t\tMENTORS : Prof.Imran Mughal & Ma'am Maryam " <<endl ;
	cout<<"\n\t\t\tTo Go Back(enter 2)"<<endl ;
	cin>>filter ;
	system("cls");
}
	if(choice==7){
	cout<<"\n   I Syed Hussain Shah Thank My Mentors Who Made Me Able To Make A Program " ;
	cout<<"Like This. With Their Brilliant And Effective Strategies & Methods Of Making ";
	cout<<"Us Able To Learn. It Is Not About The Person Who Is Learning It Is About The Teacher ";
	cout<<"Who Is Teaching. Hats Off To Prof.Imran Mughal & Ma'am Maryam May Allah Protect You ";
	cout<<"From Evil Eyes Ameen ! " <<endl ; 
	cout<<"\n\t\t\tTo Go Back(enter 2) : " ;
	cin>>filter ;
	system("cls");
	}
	if(choice==8){
		exit(0);
	}
}

    while(filter==2);            //USING DO-WHILE LOOP
    system("pause");
    return 0 ;
}




